#!/bin/bash

dir=./tmp/"${1//\//,}"

if [[ ! -d "$dir"  ]]; then
	mkdir "$dir"
fi

sshfs "$1" "$dir"
echo "Mounted $dir"


trap "echo Unmounting..." EXIT
trap "fusermount -u '$dir'" EXIT
trap "rmdir '$dir'" EXIT

if [ "$2" != "" ]; then
	nohup "${@:2}" "$dir" &
fi

sleep infinity
